name: Spelling

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@c5680ec91f7b9b91406fab4ded5d45245abf7b67
      - run: make spelling
